/**
 * @module components/ui
 * This directory contains all the UI components used in the application.
 * @file components/ui/_doc_for_files_in_this_dir.ts
 * This file is used to create a documentation for all the files in this directory.
 * The files in this directory are self explanatory. and generally contains UI components.
 * These are generated by Shadcn-ui
 * @see https://ui.shadcn.com
 */
